#!/usr/bin/env bash
# Ephemeral Compose overlays for bench (no committed one-off YAML files).
#
# Cont-batching is a process CLI flag (--no-cont-batching), not an INI key.
# Scenario 07 toggles it only for the A/B run via a temp overlay matching the
# Nix-image command style in compose.yaml / compose.bench.yaml.
#
# Usage (after PROJECT_ROOT is set):
#   source tools/bench/lib/compose_overlay.sh
#   overlay="$(bench_write_nocb_overlay llama-lab)"   # empty string if not needed
#   docker compose -f compose.yaml ${overlay:+-f "$overlay"} …
#   bench_rm_overlay "$overlay"
set -euo pipefail

# Write overlay that appends --no-cont-batching to a service command.
# Args match compose.yaml / compose.bench.yaml (entrypoint = /bin/llama-server).
# Prints absolute path to the temp file.
bench_write_nocb_overlay() {
  local service="${1:?service name}"
  local sleep_idle="${2:-900}"
  local tmp
  tmp="$(mktemp "${TMPDIR:-/tmp}/compose-nocb-${service}.XXXXXX.yaml")"
  cat >"$tmp" <<EOF
# ephemeral — generated by tools/bench/lib/compose_overlay.sh (do not commit)
services:
  ${service}:
    command:
      [
        "--host", "0.0.0.0",
        "--port", "8080",
        "--models-preset", "/etc/llama-cpp/models.ini",
        "--models-max", "1",
        "--sleep-idle-seconds", "${sleep_idle}",
        "--no-cont-batching",
      ]
EOF
  printf '%s\n' "$tmp"
}

bench_rm_overlay() {
  local path="${1:-}"
  [[ -n "$path" && -f "$path" ]] || return 0
  if command -v rm >/dev/null 2>&1; then
    rm -f "$path"
  else
    /bin/rm -f "$path" 2>/dev/null || true
  fi
}
