#!/usr/bin/env bash
# Ephemeral Compose overlays for bench (no /tmp — uses output/bench/.scratch).
#
# Cont-batching is a process CLI flag (--no-cont-batching), not an INI key.
# Scenario 07 toggles it only for the A/B run via a scratch overlay matching the
# Nix-image command style in compose.yaml / compose.bench.yaml.
#
# Usage (after PROJECT_ROOT is set):
#   source tools/bench/lib/compose_overlay.sh
#   overlay="$(bench_write_nocb_overlay llama-lab)"
#   docker compose -f compose.yaml ${overlay:+-f "$overlay"} …
#   bench_rm_overlay "$overlay"
set -euo pipefail

bench_overlay_scratch() {
  local root="${PROJECT_ROOT:-}"
  if [[ -z "$root" ]]; then
    root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
  fi
  local d="$root/output/bench/.scratch"
  mkdir -p "$d"
  printf '%s\n' "$d"
}

# Write overlay that appends --no-cont-batching to a service command.
# Prints absolute path under output/bench/.scratch/
bench_write_nocb_overlay() {
  local service="${1:?service name}"
  local sleep_idle="${2:-900}"
  local tmp
  tmp="$(bench_overlay_scratch)/compose-nocb-${service}-$$-$RANDOM.yaml"
  cat >"$tmp" <<EOF
# ephemeral — generated by tools/bench/lib/compose_overlay.sh (do not commit)
services:
  ${service}:
    command:
      [
        "--host", "0.0.0.0",
        "--port", "8080",
        "--models-preset", "/etc/llama-cpp/models.ini",
        "--models-max", "1",
        "--sleep-idle-seconds", "${sleep_idle}",
        "--no-cont-batching",
      ]
EOF
  printf '%s\n' "$tmp"
}

bench_rm_overlay() {
  local path="${1:-}"
  [[ -n "$path" && -f "$path" ]] || return 0
  rm -f "$path" 2>/dev/null || true
}
