#!/usr/bin/env bash
# Sync models-bench.ini (+ -b) from sticky/lab presets. Strips load-on-startup.
set -euo pipefail

# Expects: PROJECT_ROOT, CAPACITY_INI_A, CAPACITY_INI_B, bench_python, log, die

CAPACITY_SYNC_SOURCES="${CAPACITY_SYNC_SOURCES:-coder,chat}"
# coder → models-coder.ini, chat → models.ini, lab → models-lab.ini

sync_bench_inis() {
  local sources="${1:-$CAPACITY_SYNC_SOURCES}"
  local models_root="${PROJECT_ROOT}/models"
  local out_a="${CAPACITY_INI_A:-$PROJECT_ROOT/models-bench.ini}"
  local out_b="${CAPACITY_INI_B:-$PROJECT_ROOT/models-bench-b.ini}"

  bench_python - "$PROJECT_ROOT" "$sources" "$out_a" "$out_b" "$models_root" <<'PY'
import os, sys
from pathlib import Path

root, sources_csv, out_a, out_b, models_root = sys.argv[1:6]
src_map = {
    "coder": "models-coder.ini",
    "chat": "models.ini",
    "lab": "models-lab.ini",
}

def parse_ini(path: Path):
    """Return ordered {section: [(key, val), ...]} — only active (non-; ) sections."""
    text = path.read_text(encoding="utf-8")
    sections = {}
    order = []
    cur = None
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith(";"):
            continue
        if line.startswith("[") and line.endswith("]"):
            cur = line[1:-1].strip()
            if cur not in sections:
                sections[cur] = []
                order.append(cur)
            continue
        if cur is None or "=" not in line:
            continue
        k, _, v = line.partition("=")
        k, v = k.strip(), v.strip()
        # last wins within section
        sections[cur] = [(kk, vv) for kk, vv in sections[cur] if kk != k]
        sections[cur].append((k, v))
    return order, sections

def gguf_exists(rel: str) -> bool:
    if not rel:
        return False
    # paths in ini are /models/... inside container → host ./models/...
    p = rel
    if p.startswith("/models/"):
        p = p[len("/models/"):]
    elif p.startswith("models/"):
        p = p[len("models/"):]
    host = Path(models_root) / p
    if host.is_file():
        return True
    # multipart: first shard
    if host.with_name(host.name).exists():
        return True
    # allow missing locally (server may have weights); warn via empty check only if any exist
    return False

merged_order = []
merged = {}
seen = set()
any_disk_check = Path(models_root).is_dir() and any(Path(models_root).rglob("*.gguf"))

for key in [s.strip() for s in sources_csv.split(",") if s.strip()]:
    fname = src_map.get(key)
    if not fname:
        print(f"[bench capacity] warn: unknown sync source '{key}' (use coder,chat,lab)", file=sys.stderr)
        continue
    path = Path(root) / fname
    if not path.is_file():
        print(f"[bench capacity] warn: missing {fname}", file=sys.stderr)
        continue
    order, sections = parse_ini(path)
    for name in order:
        keys = {k: v for k, v in sections[name]}
        if "model" not in keys:
            continue
        if any_disk_check and not gguf_exists(keys["model"]):
            print(f"[bench capacity] skip (gguf missing): {name}", file=sys.stderr)
            continue
        # later sources do not override earlier (coder > chat > lab if listed that way)
        if name in seen:
            continue
        seen.add(name)
        # Bench defaults: no sticky load, fit off, np=1 for clean capacity curves
        pairs = [(k, v) for k, v in sections[name] if k != "load-on-startup"]
        forced = {"fit": "off", "np": "1"}
        out_pairs = []
        seen_k = set()
        for k, v in pairs:
            if k in forced:
                out_pairs.append((k, forced[k]))
            else:
                out_pairs.append((k, v))
            seen_k.add(k)
        for k, v in forced.items():
            if k not in seen_k:
                out_pairs.append((k, v))
        merged[name] = out_pairs
        merged_order.append(name)

header = [
    "; AUTO-GENERATED by ./bench capacity sync — do not edit by hand.",
    "; Sources: " + sources_csv,
    "; Stickys (models.ini / models-coder.ini) are never modified by capacity.",
    "; load-on-startup stripped; fit=off; missing GGUFs skipped when ./models has weights.",
    "",
]

def render(order, sections):
    lines = list(header)
    if not order:
        lines.append("; (no sections — check CAPACITY_SYNC_SOURCES / GGUF paths)")
        lines.append("")
        return "\n".join(lines)
    for name in order:
        lines.append(f"[{name}]")
        for k, v in sections[name]:
            lines.append(f"{k} = {v}")
        lines.append("")
    return "\n".join(lines)

body = render(merged_order, merged)
Path(out_a).write_text(body, encoding="utf-8")
Path(out_b).write_text(body, encoding="utf-8")
print(f"synced {len(merged_order)} model(s) → {os.path.basename(out_a)} + {os.path.basename(out_b)}")
for n in merged_order:
    print(f"  - {n}")
PY
}

list_bench_models() {
  bench_python - "$CAPACITY_INI_A" <<'PY'
import sys
path = sys.argv[1]
try:
    with open(path, encoding="utf-8") as f:
        for raw in f:
            line = raw.strip()
            if line.startswith("[") and line.endswith("]") and not line.startswith(";"):
                print(line[1:-1].strip())
except FileNotFoundError:
    pass
PY
}

# Resolve models for capacity/matrix runs.
# Env:
#   CAPACITY_MODELS=A,B,C   preferred filter (exact or unique substring)
#   CAPACITY_MODEL=A[,B]    legacy / also accepts comma list if MODELS empty
#   CAPACITY_NO_VL=1        drop sections ending in -VL
# Prints one section name per line. Dies if filter matches nothing / ambiguous.
resolve_bench_models() {
  local filter="${CAPACITY_MODELS:-${CAPACITY_MODEL:-}}"
  local no_vl="${CAPACITY_NO_VL:-0}"
  bench_python - "$CAPACITY_INI_A" "$filter" "$no_vl" <<'PY'
import sys
from pathlib import Path

path, filt, no_vl = sys.argv[1], sys.argv[2].strip(), sys.argv[3] == "1"
available = []
try:
    text = Path(path).read_text(encoding="utf-8")
except FileNotFoundError:
    text = ""
for raw in text.splitlines():
    line = raw.strip()
    if line.startswith("[") and line.endswith("]") and not line.startswith(";"):
        available.append(line[1:-1].strip())

if no_vl:
    available = [m for m in available if not m.endswith("-VL")]

if not filt:
    for m in available:
        print(m)
    raise SystemExit(0)

want = [x.strip() for x in filt.split(",") if x.strip()]
chosen = []
errors = []

def resolve_one(w: str):
    if w in available:
        return w, None
    # Prefer prefix matches (avoids Cyber-* matching bare Tiel-*)
    prefixes = [m for m in available if m.startswith(w)]
    pool = prefixes if prefixes else [m for m in available if w in m]
    if not w.endswith("-VL"):
        non_vl = [m for m in pool if not m.endswith("-VL")]
        if non_vl:
            pool = non_vl
    if len(pool) == 1:
        return pool[0], None
    if len(pool) == 0:
        return None, f"no match for {w!r}"
    preview = ", ".join(pool[:8])
    more = "" if len(pool) <= 8 else f" (+{len(pool) - 8})"
    tip = " (add --no-vl or use a longer / exact name)" if any(m.endswith("-VL") for m in available) else ""
    return None, f"ambiguous {w!r} → {preview}{more}{tip}"

for w in want:
    name, err = resolve_one(w)
    if err:
        errors.append(err)
    else:
        chosen.append(name)

# de-dupe preserve order
seen = set()
out = []
for m in chosen:
    if m not in seen:
        seen.add(m)
        out.append(m)

if errors:
    avail = ", ".join(available) if available else "(none — sync / GGUFs?)"
    print(
        "error: model filter failed:\n  - "
        + "\n  - ".join(errors)
        + f"\navailable ({len(available)}): {avail}",
        file=sys.stderr,
    )
    raise SystemExit(2)
if not out:
    print("error: model filter matched nothing", file=sys.stderr)
    raise SystemExit(2)
for m in out:
    print(m)
PY
}
