#!/usr/bin/env bash
# Fetch / update the llama.cpp source tree used by ./build-nix-image.sh
#
# Default pin is a temporary fork for models/MTP features not yet in upstream.
# When ggml-org/llama.cpp catches up, switch:
#   LLAMA_REPO=https://github.com/ggml-org/llama.cpp.git LLAMA_REF=master ./scripts/fetch-llama.sh
#
# Env:
#   LLAMA_REPO   git URL (default: danielhanchen fork)
#   LLAMA_REF    branch | tag | commit (default: qwen4exp/mtp)
#   LLAMA_DIR    checkout path (default: .build/llama.cpp)
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LLAMA_REPO="${LLAMA_REPO:-https://github.com/danielhanchen/llama.cpp.git}"
LLAMA_REF="${LLAMA_REF:-qwen4exp/mtp}"
LLAMA_DIR="${LLAMA_DIR:-$ROOT/.build/llama.cpp}"
PIN_FILE="$ROOT/.build/llama.pin"

mkdir -p "$(dirname "$LLAMA_DIR")"

echo "=== fetch llama.cpp ==="
echo "  repo: $LLAMA_REPO"
echo "  ref:  $LLAMA_REF"
echo "  dir:  $LLAMA_DIR"
echo ""

if [[ -d "$LLAMA_DIR/.git" ]]; then
  git -C "$LLAMA_DIR" remote set-url origin "$LLAMA_REPO"
  git -C "$LLAMA_DIR" fetch --depth 1 origin "$LLAMA_REF"
  # Detach at fetched tip (works for branch or sha)
  if git -C "$LLAMA_DIR" rev-parse --verify "FETCH_HEAD" >/dev/null 2>&1; then
    git -C "$LLAMA_DIR" checkout --detach FETCH_HEAD
  else
    git -C "$LLAMA_DIR" fetch --depth 1 origin "+refs/heads/${LLAMA_REF}:refs/remotes/origin/${LLAMA_REF}" || true
    git -C "$LLAMA_DIR" checkout --detach "origin/${LLAMA_REF}" 2>/dev/null \
      || git -C "$LLAMA_DIR" checkout "$LLAMA_REF"
  fi
else
  rm -rf "$LLAMA_DIR"
  git clone --depth 1 --branch "$LLAMA_REF" "$LLAMA_REPO" "$LLAMA_DIR" \
    || git clone --depth 1 "$LLAMA_REPO" "$LLAMA_DIR" && git -C "$LLAMA_DIR" checkout --detach "$LLAMA_REF"
fi

COMMIT="$(git -C "$LLAMA_DIR" rev-parse HEAD)"
SHORT="$(git -C "$LLAMA_DIR" rev-parse --short HEAD)"
DATE_UTC="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

cat >"$PIN_FILE" <<EOF
# Generated by scripts/fetch-llama.sh — do not edit by hand for builds; re-run the script.
repo=$LLAMA_REPO
ref=$LLAMA_REF
commit=$COMMIT
fetched_at=$DATE_UTC
EOF

# Also keep a short tracked tip for docs (optional commit of this file)
mkdir -p "$ROOT/docs"
cat >"$ROOT/docs/llama-pin.md" <<EOF
# llama.cpp build pin

| | |
|---|---|
| Repo | \`$LLAMA_REPO\` |
| Ref | \`$LLAMA_REF\` |
| Commit | \`$SHORT\` (\`$COMMIT\`) |
| Fetched | $DATE_UTC |

Update on the build host:

\`\`\`bash
./scripts/fetch-llama.sh
./build-nix-image.sh
\`\`\`

When upstream has the needed model/MTP support:

\`\`\`bash
LLAMA_REPO=https://github.com/ggml-org/llama.cpp.git LLAMA_REF=master ./scripts/fetch-llama.sh
\`\`\`
EOF

echo "✓ Checked out $SHORT"
echo "  Pin written to $PIN_FILE and docs/llama-pin.md"
echo "  Next: ./build-nix-image.sh"
